### ISSUE TITLE
Using noexcept function 这个文章你为啥不加.md后缀

### ISSUE THREAD

**Issue by zer0pwned** [AntiMoron/cpp-article#2]
这样的话就直接可以预览了，不用你open issue去预览md了

**Comment by AM-young-fun** [comment]
## 单纯因为我昨天脑袋不好使了。

**Comment by zer0pwned** [comment]
## 听说你司今日门口有草泥马出没，你家老板IPO挣这么多有没有给你发福利？

**Comment by AM-young-fun** [comment]
- 发个JB屁。我算老几。

**Comment by zer0pwned** [comment]
> 口胡，你这么吊，他们不给你发房子已经够让我生气的了！

**Comment by AM-young-fun** [comment]
``` bash
房子都是浮云.
```

**Comment by AM-young-fun** [comment]
..test,

**Comment by zer0pwned** [comment]
Test毛线？

发件人: Anti_Moron [mailto:notifications@github.com] 
发送时间: 2014年9月11日 14:38
收件人: AntiMoron/cpp-article
抄送: Marvin
主题: Re: [cpp-article] Using noexcept function 这个文章你为啥不加.md后缀 (#2)

..test,

**Comment by AM-young-fun** [comment]
> 我怕我streak断掉。我今天上午看还因为时差没刷出今天。现在好了，我应该commit下。

**Comment by zer0pwned** [comment]
# 哈哈哈你无聊不？果然大家都是streak一长就怕断掉啊！

**Comment by AM-young-fun** [comment]
......

> "果然大家"
> 
> ###### 你他妈不也一样！还说我无聊！？

**Comment by zer0pwned** [comment]
你无聊不无聊，你居然为了实验github的markdown语法一天push了15个commit！？

**Comment by AM-young-fun** [comment]
我测试一下anchor你有意见么？

> 顺便今日打卡。

**Comment by zer0pwned** [comment]
我發現了一個不讓streak斷掉的好方法，修改系統時間然後提交就行了，今天在虛擬機裏提交的東西發現全你媽到亮在了兩個星期之前，我操！一看發現是因爲當時關虛擬機執行的是暫停，恍恍惚惚號。

麻痹阿里大吊請我吃飯！！！

**Comment by AM-young-fun** [comment]
好！何厚铧恍恍惚惚红红火火

2014-10-20 18:05 GMT+08:00 Marvin notifications@github.com:
